# Generated by Django 5.1.3 on 2025-02-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
