# Generated by Django 5.1.3 on 2025-03-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_db', '0003_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='coordinates',
        ),
    ]
