# Generated by Django 5.1.3 on 2025-03-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_db', '0004_remove_restaurant_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='restaurants',
            field=models.ManyToManyField(related_name='dishes', to='platform_db.restaurant'),
        ),
    ]
