# Generated by Django 5.1.3 on 2025-03-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_db', '0005_dish_restaurants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
    ]
