# Generated by Django 5.1.3 on 2025-03-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_db', '0008_purchase_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='date',
        ),
    ]
