# Generated by Django 5.1.3 on 2025-03-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_db', '0009_remove_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
