# Generated by Django 5.1.3 on 2025-04-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_db', '0010_generalcomment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
