# Generated by Django 5.1.3 on 2025-04-11 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_db', '0011_customuser_is_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
