# Generated by Django 5.1.3 on 2025-04-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_db', '0012_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
