# Generated by Django 5.1.3 on 2025-04-12 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_db', '0013_customuser_is_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('picked', 'Picked'), ('delivered', 'Delivered')], default='assigned', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(limit_choices_to={'is_delivery': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='platform_db.purchase')),
            ],
        ),
    ]
