# Generated by Django 5.1.3 on 2025-04-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_db', '0014_deliveryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcomment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalcomment',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
